grid:
  range:
    min: 0
    max: 30.0
  cell:
    size: 0.2
    height: 0.2
  segments: 720

# semantic:
#   edge_detection:
#     perform: false
#     min: 5
#     max: 120
#     kernel: 3

ransac:
  tolerance: 0.2
  iterations: 50

lidar:
  height: 0.5
  z_min: -2
