grid:
  range:
    min: 0
    max: 83.0
  cell:
    size: 0.25
    height: 1
  segments: 240

semantic:
  edge_detection:
    perform: false
    min: 5
    max: 120
    kernel: 3

ransac:
  tolerance: 0.2
  iterations: 50

lidar:
  height: 0.5
  z_min: -1
